XiaoMi/mace

tools/sh_commands.py
Some devices generate `adb devices` message with `-` which
is ignored by current tools. This patch enables them.
=> tools: support more adb device scenarios

docs/user_guide/basic_usage.rst
According to [tools/converter.py](https://github.com/XiaoMi/mace/blob/master/tools/converter.py/#L47), it should be `builds/` not `build/`.
Efforts to find the converted model file.
=> fix converted model folder description error in docs

mace/python/tools/str2vec_maps.cc.jinja2
When running the bazel build commands using python3 I would get this error:
```
ERROR: /home/user/XiaoMi/mace-master/mace/codegen/BUILD:22:1: no such target '@local_opencl_kernel_encrypt//:gen/encrypt_opencl_kernel': target 'gen/encrypt_opencl_kernel' not declared in package ''
```
After changing the code above the issue was resolved.
I checked the template again in python2.7 and it still runs, so I think .items() works here.
=> Made str2vec_maps.cc.jinja2 template python 2.7 & Python 3+ compatible

mace/ops/opencl/image/depth_to_space.h
In the definition of `MaceStatus DepthToSpaceKernel<T>::Compute` method, an unknown identifier is used due to, probably, copy-paste error:
`const char *kernel_name = kernel_name = "depth_to_space";`
Note that, this causes compilation errors.
=> Removed erroneous use of undeclared name

mace/core/types.cc
Typename string and byte-size returned by functions `DataTypeToString` and `GetEnumTypeSize` for `DT_INT32` changed from `"DT_UINT32"` and `sizeof(uint32_t)` to `"DT_INT32"` and `sizeof(int32_t)` respectively for consistency's sake.
=> Typename changed from uint32_t to int32_t

mace/ops/opencl/cl/eltwise.cl
Non-pointwise (i.e. kernel size != 1x1) convolutions with "SAME" padding return incorrect results when applied after element-wise division. This occurs only when both tensor operands of division have the same number of channels `C`, where `C` is not a multiply of 4, because of zero-padding applied to such tensors.
The source of the problem is performing division on channel pads which are filled by zeros - since both sides of division are zeros this operation returns `NaN` (see: The OpenCL Specification: 6.3 Operators & IEEE Standard for Floating-Point Arithmetic: 7.2 Invalid operation).
The problem is not limited to division. In case of `pow` function it is even more dangerous: instruction `pow(0., 0.)` returns `1` (see: The OpenCL Specification: 7.5 Edge Case Behavior), so there's no …
=> Fixed NaN propagation from channel paddings on GPU

mace/ops/eltwise_test.cc, mace/ops/opencl/cl/eltwise.cl
Fixed bug in OpenCL implementation of ElwiseOp: invalid input image coordinates in case of broadcasting on channel dimension (`INPUT_TYPE == 4`). Incorrect results of this operation are observable only when one of the input tensors has >4 channels.
=> Fix broadcasting on channel dimension in EltwiseOp for GPU

mace/python/tools/converter_tool/onnx_converter.py
Fix https://github.com/XiaoMi/mace/issues/383
Onnx node dosen't have name, then using output name instead.
=> fix blank name for onnx model, use output name instead

tools/python/transform/caffe_converter.py
Roll back to `convert_crop` as in MACE v0.10.0 and support `len(paramo.offset)==1`
=> Fix convert_crop Caffe

tools/python/transform/onnx_converter.py
Hi there, thanks for your library!
I've added support of Upsample operator to onnx convertor. Should work with all opset <=10. (I use onnx==1.3.0 in my experiments)
The only limitation - user have to run shape inference before exporting to onnx.
=> Add support of upsample operator in onnx convertor

docs/development/data_format.md
Link was broken after refactoring at https://github.com/XiaoMi/mace/commit/320b509c79bbf073f04ec5da07c201f6bffb98f9
=> Fix outdated link to base_converter.py.

tools/device.py
If there are unauthorized devices `list_adb_devices(cls)` fails.
We can reuse `sh_commands.adb_devices()` that correctly filters out unauthorized devices.
=> Fix adb permissions

third_party/caffe/Dockerfile, third_party/caffe/caffe.proto, tools/python/transform/caffe_converter.py
Currently `ReLU6` isn't supported in CAFFE, therefore it's not implemented in MACE for CAFFE as well. But `master` branch of CAFFE includes a `Clip` op that can be used to limit input tensor within a specific range. 
We can use CAFFE `Clip` layer to implement `ReLU6` op in CAFFE and consequently in MACE for CAFFE.
I've already tested these modifications with mobilenetv2-like models and conversion/run/validation are successful (to run validation, first delete old caffe container/image to let MACE build the new one).
=> Add support for ReLU6 op in CAFFE

tools/device.py
Fix: Messages from `mace_run.cc` is printed as `Bytes`
=> Let `subprocess.Popen` open outputs in text mode

tools/validate.py
When an argument has zero norm, `calculate_similarity` returns an Int, which results to an error in `compare_output`: `TypeError: '>' not supported between instances of 'int' and 'tuple'`
=> Fix an edge case involving similarity between zero outputs

mace/codegen/CMakeLists.txt, mace/core/CMakeLists.txt, mace/libmace/CMakeLists.txt, mace/libmace/mace.mri.in, mace/ops/CMakeLists.txt, mace/port/CMakeLists.txt, mace/port/android/CMakeLists.txt, mace/port/darwin/CMakeLists.txt, mace/port/linux/CMakeLists.txt, mace/port/linux_base/CMakeLists.txt, mace/port/posix/CMakeLists.txt, mace/port/windows/CMakeLists.txt, mace/proto/CMakeLists.txt, mace/utils/CMakeLists.txt, third_party/protobuf/protobuf.cmake, third_party/rpcmem/rpcmem.cmake
This PR addresses issue: https://github.com/XiaoMi/mace/issues/698
With the provided code, MACE static library is correctly built and installed. It can then be used to run models, tests, benchmarks and used in other projects.
=> Fix: CMake static library

mace/tools/CMakeLists.txt
A previous commit has removed `model` target from `target_link_libraries` of `mace_run` target. Without that, MACE build fails when `RUNMODE=code`.
=> Fix mace_run not linking model library

mace/ops/depthwise_deconv2d.cc
Since MACE `v1.0.0`, for some unknown reasons, `host` target support for `depthwise_deconv2d` has been dropped. This MR solves that issue.
=> Fix host target not supported in depthwise_deconv2d

mace/runtimes/apu/v4/neuron_delegate_kernel.cc
APU V4: Update `NeuronCompilation_setSWDilatedConv` usage to be compatible with earlier versions of APU library.
=> fix: update API usage for APU V4 library compatibility  

include/mace/public/mace.h, mace/flows/apu/apu_ref_flow.cc, mace/runtimes/apu/v4/apu_wrapper.cc, mace/runtimes/apu/v4/neuron_delegate_kernel.cc, mace/runtimes/apu/v4/neuron_delegate_kernel.h, mace/tools/mace_run.cc, tools/converter.py, tools/device.py
add policy `APU_CACHE_LOAD_OR_STORE`:   
1) try  load cache first
2) if cache is outdated or absent, re-compile and store
the flags in `mace_run` will be
```
--accelerator_cache_policy=3 
--accelerator_binary_file=path_to_cache
```
=>  feat: support APU_CACHE_LOAD_OR_STORE policy to keep cache updated
